/*
Xero Accounting API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.1
Contact: api@xero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchPaymentDelete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchPaymentDelete{}

// BatchPaymentDelete struct for BatchPaymentDelete
type BatchPaymentDelete struct {
	// The Xero generated unique identifier for the bank transaction (read-only)
	BatchPaymentID string `json:"BatchPaymentID"`
	// The status of the batch payment.
	Status string `json:"Status"`
}

type _BatchPaymentDelete BatchPaymentDelete

// NewBatchPaymentDelete instantiates a new BatchPaymentDelete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchPaymentDelete(batchPaymentID string, status string) *BatchPaymentDelete {
	this := BatchPaymentDelete{}
	this.BatchPaymentID = batchPaymentID
	this.Status = status
	return &this
}

// NewBatchPaymentDeleteWithDefaults instantiates a new BatchPaymentDelete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchPaymentDeleteWithDefaults() *BatchPaymentDelete {
	this := BatchPaymentDelete{}
	var status string = "DELETED"
	this.Status = status
	return &this
}

// GetBatchPaymentID returns the BatchPaymentID field value
func (o *BatchPaymentDelete) GetBatchPaymentID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchPaymentID
}

// GetBatchPaymentIDOk returns a tuple with the BatchPaymentID field value
// and a boolean to check if the value has been set.
func (o *BatchPaymentDelete) GetBatchPaymentIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchPaymentID, true
}

// SetBatchPaymentID sets field value
func (o *BatchPaymentDelete) SetBatchPaymentID(v string) {
	o.BatchPaymentID = v
}

// GetStatus returns the Status field value
func (o *BatchPaymentDelete) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BatchPaymentDelete) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BatchPaymentDelete) SetStatus(v string) {
	o.Status = v
}

func (o BatchPaymentDelete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchPaymentDelete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["BatchPaymentID"] = o.BatchPaymentID
	toSerialize["Status"] = o.Status
	return toSerialize, nil
}

func (o *BatchPaymentDelete) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"BatchPaymentID",
		"Status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchPaymentDelete := _BatchPaymentDelete{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchPaymentDelete)

	if err != nil {
		return err
	}

	*o = BatchPaymentDelete(varBatchPaymentDelete)

	return err
}

type NullableBatchPaymentDelete struct {
	value *BatchPaymentDelete
	isSet bool
}

func (v NullableBatchPaymentDelete) Get() *BatchPaymentDelete {
	return v.value
}

func (v *NullableBatchPaymentDelete) Set(val *BatchPaymentDelete) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchPaymentDelete) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchPaymentDelete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchPaymentDelete(val *BatchPaymentDelete) *NullableBatchPaymentDelete {
	return &NullableBatchPaymentDelete{value: val, isSet: true}
}

func (v NullableBatchPaymentDelete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchPaymentDelete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


