/*
Xero Accounting API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.1
Contact: api@xero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// CountryCode the model 'CountryCode'
type CountryCode string

// List of CountryCode
const (
	AD_CountryCode CountryCode = "AD"
	AE_CountryCode CountryCode = "AE"
	AF_CountryCode CountryCode = "AF"
	AG_CountryCode CountryCode = "AG"
	AI_CountryCode CountryCode = "AI"
	AL_CountryCode CountryCode = "AL"
	AM_CountryCode CountryCode = "AM"
	AN_CountryCode CountryCode = "AN"
	AO_CountryCode CountryCode = "AO"
	AQ_CountryCode CountryCode = "AQ"
	AR_CountryCode CountryCode = "AR"
	AS_CountryCode CountryCode = "AS"
	AT_CountryCode CountryCode = "AT"
	AU_CountryCode CountryCode = "AU"
	AW_CountryCode CountryCode = "AW"
	AZ_CountryCode CountryCode = "AZ"
	BA_CountryCode CountryCode = "BA"
	BB_CountryCode CountryCode = "BB"
	BD_CountryCode CountryCode = "BD"
	BE_CountryCode CountryCode = "BE"
	BF_CountryCode CountryCode = "BF"
	BG_CountryCode CountryCode = "BG"
	BH_CountryCode CountryCode = "BH"
	BI_CountryCode CountryCode = "BI"
	BJ_CountryCode CountryCode = "BJ"
	BL_CountryCode CountryCode = "BL"
	BM_CountryCode CountryCode = "BM"
	BN_CountryCode CountryCode = "BN"
	BO_CountryCode CountryCode = "BO"
	BR_CountryCode CountryCode = "BR"
	BS_CountryCode CountryCode = "BS"
	BT_CountryCode CountryCode = "BT"
	BW_CountryCode CountryCode = "BW"
	BY_CountryCode CountryCode = "BY"
	BZ_CountryCode CountryCode = "BZ"
	CA_CountryCode CountryCode = "CA"
	CC_CountryCode CountryCode = "CC"
	CD_CountryCode CountryCode = "CD"
	CF_CountryCode CountryCode = "CF"
	CG_CountryCode CountryCode = "CG"
	CH_CountryCode CountryCode = "CH"
	CI_CountryCode CountryCode = "CI"
	CK_CountryCode CountryCode = "CK"
	CL_CountryCode CountryCode = "CL"
	CM_CountryCode CountryCode = "CM"
	CN_CountryCode CountryCode = "CN"
	CO_CountryCode CountryCode = "CO"
	CR_CountryCode CountryCode = "CR"
	CU_CountryCode CountryCode = "CU"
	CV_CountryCode CountryCode = "CV"
	CW_CountryCode CountryCode = "CW"
	CX_CountryCode CountryCode = "CX"
	CY_CountryCode CountryCode = "CY"
	CZ_CountryCode CountryCode = "CZ"
	DE_CountryCode CountryCode = "DE"
	DJ_CountryCode CountryCode = "DJ"
	DK_CountryCode CountryCode = "DK"
	DM_CountryCode CountryCode = "DM"
	DO_CountryCode CountryCode = "DO"
	DZ_CountryCode CountryCode = "DZ"
	EC_CountryCode CountryCode = "EC"
	EE_CountryCode CountryCode = "EE"
	EG_CountryCode CountryCode = "EG"
	EH_CountryCode CountryCode = "EH"
	ER_CountryCode CountryCode = "ER"
	ES_CountryCode CountryCode = "ES"
	ET_CountryCode CountryCode = "ET"
	FI_CountryCode CountryCode = "FI"
	FJ_CountryCode CountryCode = "FJ"
	FK_CountryCode CountryCode = "FK"
	FM_CountryCode CountryCode = "FM"
	FO_CountryCode CountryCode = "FO"
	FR_CountryCode CountryCode = "FR"
	GA_CountryCode CountryCode = "GA"
	GB_CountryCode CountryCode = "GB"
	GD_CountryCode CountryCode = "GD"
	GE_CountryCode CountryCode = "GE"
	GG_CountryCode CountryCode = "GG"
	GH_CountryCode CountryCode = "GH"
	GI_CountryCode CountryCode = "GI"
	GL_CountryCode CountryCode = "GL"
	GM_CountryCode CountryCode = "GM"
	GN_CountryCode CountryCode = "GN"
	GQ_CountryCode CountryCode = "GQ"
	GR_CountryCode CountryCode = "GR"
	GT_CountryCode CountryCode = "GT"
	GU_CountryCode CountryCode = "GU"
	GW_CountryCode CountryCode = "GW"
	GY_CountryCode CountryCode = "GY"
	HK_CountryCode CountryCode = "HK"
	HN_CountryCode CountryCode = "HN"
	HR_CountryCode CountryCode = "HR"
	HT_CountryCode CountryCode = "HT"
	HU_CountryCode CountryCode = "HU"
	ID_CountryCode CountryCode = "ID"
	IE_CountryCode CountryCode = "IE"
	IL_CountryCode CountryCode = "IL"
	IM_CountryCode CountryCode = "IM"
	IN_CountryCode CountryCode = "IN"
	IO_CountryCode CountryCode = "IO"
	IQ_CountryCode CountryCode = "IQ"
	IR_CountryCode CountryCode = "IR"
	IS_CountryCode CountryCode = "IS"
	IT_CountryCode CountryCode = "IT"
	JE_CountryCode CountryCode = "JE"
	JM_CountryCode CountryCode = "JM"
	JO_CountryCode CountryCode = "JO"
	JP_CountryCode CountryCode = "JP"
	KE_CountryCode CountryCode = "KE"
	KG_CountryCode CountryCode = "KG"
	KH_CountryCode CountryCode = "KH"
	KI_CountryCode CountryCode = "KI"
	KM_CountryCode CountryCode = "KM"
	KN_CountryCode CountryCode = "KN"
	KP_CountryCode CountryCode = "KP"
	KR_CountryCode CountryCode = "KR"
	KW_CountryCode CountryCode = "KW"
	KY_CountryCode CountryCode = "KY"
	KZ_CountryCode CountryCode = "KZ"
	LA_CountryCode CountryCode = "LA"
	LB_CountryCode CountryCode = "LB"
	LC_CountryCode CountryCode = "LC"
	LI_CountryCode CountryCode = "LI"
	LK_CountryCode CountryCode = "LK"
	LR_CountryCode CountryCode = "LR"
	LS_CountryCode CountryCode = "LS"
	LT_CountryCode CountryCode = "LT"
	LU_CountryCode CountryCode = "LU"
	LV_CountryCode CountryCode = "LV"
	LY_CountryCode CountryCode = "LY"
	MA_CountryCode CountryCode = "MA"
	MC_CountryCode CountryCode = "MC"
	MD_CountryCode CountryCode = "MD"
	ME_CountryCode CountryCode = "ME"
	MF_CountryCode CountryCode = "MF"
	MG_CountryCode CountryCode = "MG"
	MH_CountryCode CountryCode = "MH"
	MK_CountryCode CountryCode = "MK"
	ML_CountryCode CountryCode = "ML"
	MM_CountryCode CountryCode = "MM"
	MN_CountryCode CountryCode = "MN"
	MO_CountryCode CountryCode = "MO"
	MP_CountryCode CountryCode = "MP"
	MR_CountryCode CountryCode = "MR"
	MS_CountryCode CountryCode = "MS"
	MT_CountryCode CountryCode = "MT"
	MU_CountryCode CountryCode = "MU"
	MV_CountryCode CountryCode = "MV"
	MW_CountryCode CountryCode = "MW"
	MX_CountryCode CountryCode = "MX"
	MY_CountryCode CountryCode = "MY"
	MZ_CountryCode CountryCode = "MZ"
	NA_CountryCode CountryCode = "NA"
	NC_CountryCode CountryCode = "NC"
	NE_CountryCode CountryCode = "NE"
	NG_CountryCode CountryCode = "NG"
	NI_CountryCode CountryCode = "NI"
	NL_CountryCode CountryCode = "NL"
	NO_CountryCode CountryCode = "NO"
	NP_CountryCode CountryCode = "NP"
	NR_CountryCode CountryCode = "NR"
	NU_CountryCode CountryCode = "NU"
	NZ_CountryCode CountryCode = "NZ"
	OM_CountryCode CountryCode = "OM"
	PA_CountryCode CountryCode = "PA"
	PE_CountryCode CountryCode = "PE"
	PF_CountryCode CountryCode = "PF"
	PG_CountryCode CountryCode = "PG"
	PH_CountryCode CountryCode = "PH"
	PK_CountryCode CountryCode = "PK"
	PL_CountryCode CountryCode = "PL"
	PM_CountryCode CountryCode = "PM"
	PN_CountryCode CountryCode = "PN"
	PR_CountryCode CountryCode = "PR"
	PS_CountryCode CountryCode = "PS"
	PT_CountryCode CountryCode = "PT"
	PW_CountryCode CountryCode = "PW"
	PY_CountryCode CountryCode = "PY"
	QA_CountryCode CountryCode = "QA"
	RE_CountryCode CountryCode = "RE"
	RO_CountryCode CountryCode = "RO"
	RS_CountryCode CountryCode = "RS"
	RU_CountryCode CountryCode = "RU"
	RW_CountryCode CountryCode = "RW"
	SA_CountryCode CountryCode = "SA"
	SB_CountryCode CountryCode = "SB"
	SC_CountryCode CountryCode = "SC"
	SD_CountryCode CountryCode = "SD"
	SE_CountryCode CountryCode = "SE"
	SG_CountryCode CountryCode = "SG"
	SH_CountryCode CountryCode = "SH"
	SI_CountryCode CountryCode = "SI"
	SJ_CountryCode CountryCode = "SJ"
	SK_CountryCode CountryCode = "SK"
	SL_CountryCode CountryCode = "SL"
	SM_CountryCode CountryCode = "SM"
	SN_CountryCode CountryCode = "SN"
	SO_CountryCode CountryCode = "SO"
	SR_CountryCode CountryCode = "SR"
	SS_CountryCode CountryCode = "SS"
	ST_CountryCode CountryCode = "ST"
	SV_CountryCode CountryCode = "SV"
	SX_CountryCode CountryCode = "SX"
	SY_CountryCode CountryCode = "SY"
	SZ_CountryCode CountryCode = "SZ"
	TC_CountryCode CountryCode = "TC"
	TD_CountryCode CountryCode = "TD"
	TG_CountryCode CountryCode = "TG"
	TH_CountryCode CountryCode = "TH"
	TJ_CountryCode CountryCode = "TJ"
	TK_CountryCode CountryCode = "TK"
	TL_CountryCode CountryCode = "TL"
	TM_CountryCode CountryCode = "TM"
	TN_CountryCode CountryCode = "TN"
	TO_CountryCode CountryCode = "TO"
	TR_CountryCode CountryCode = "TR"
	TT_CountryCode CountryCode = "TT"
	TV_CountryCode CountryCode = "TV"
	TW_CountryCode CountryCode = "TW"
	TZ_CountryCode CountryCode = "TZ"
	UA_CountryCode CountryCode = "UA"
	UG_CountryCode CountryCode = "UG"
	US_CountryCode CountryCode = "US"
	UY_CountryCode CountryCode = "UY"
	UZ_CountryCode CountryCode = "UZ"
	VA_CountryCode CountryCode = "VA"
	VC_CountryCode CountryCode = "VC"
	VE_CountryCode CountryCode = "VE"
	VG_CountryCode CountryCode = "VG"
	VI_CountryCode CountryCode = "VI"
	VN_CountryCode CountryCode = "VN"
	VU_CountryCode CountryCode = "VU"
	WF_CountryCode CountryCode = "WF"
	WS_CountryCode CountryCode = "WS"
	XK_CountryCode CountryCode = "XK"
	YE_CountryCode CountryCode = "YE"
	YT_CountryCode CountryCode = "YT"
	ZA_CountryCode CountryCode = "ZA"
	ZM_CountryCode CountryCode = "ZM"
	ZW_CountryCode CountryCode = "ZW"
)

// All allowed values of CountryCode enum
var AllowedCountryCodeEnumValues = []CountryCode{
	"AD",
	"AE",
	"AF",
	"AG",
	"AI",
	"AL",
	"AM",
	"AN",
	"AO",
	"AQ",
	"AR",
	"AS",
	"AT",
	"AU",
	"AW",
	"AZ",
	"BA",
	"BB",
	"BD",
	"BE",
	"BF",
	"BG",
	"BH",
	"BI",
	"BJ",
	"BL",
	"BM",
	"BN",
	"BO",
	"BR",
	"BS",
	"BT",
	"BW",
	"BY",
	"BZ",
	"CA",
	"CC",
	"CD",
	"CF",
	"CG",
	"CH",
	"CI",
	"CK",
	"CL",
	"CM",
	"CN",
	"CO",
	"CR",
	"CU",
	"CV",
	"CW",
	"CX",
	"CY",
	"CZ",
	"DE",
	"DJ",
	"DK",
	"DM",
	"DO",
	"DZ",
	"EC",
	"EE",
	"EG",
	"EH",
	"ER",
	"ES",
	"ET",
	"FI",
	"FJ",
	"FK",
	"FM",
	"FO",
	"FR",
	"GA",
	"GB",
	"GD",
	"GE",
	"GG",
	"GH",
	"GI",
	"GL",
	"GM",
	"GN",
	"GQ",
	"GR",
	"GT",
	"GU",
	"GW",
	"GY",
	"HK",
	"HN",
	"HR",
	"HT",
	"HU",
	"ID",
	"IE",
	"IL",
	"IM",
	"IN",
	"IO",
	"IQ",
	"IR",
	"IS",
	"IT",
	"JE",
	"JM",
	"JO",
	"JP",
	"KE",
	"KG",
	"KH",
	"KI",
	"KM",
	"KN",
	"KP",
	"KR",
	"KW",
	"KY",
	"KZ",
	"LA",
	"LB",
	"LC",
	"LI",
	"LK",
	"LR",
	"LS",
	"LT",
	"LU",
	"LV",
	"LY",
	"MA",
	"MC",
	"MD",
	"ME",
	"MF",
	"MG",
	"MH",
	"MK",
	"ML",
	"MM",
	"MN",
	"MO",
	"MP",
	"MR",
	"MS",
	"MT",
	"MU",
	"MV",
	"MW",
	"MX",
	"MY",
	"MZ",
	"NA",
	"NC",
	"NE",
	"NG",
	"NI",
	"NL",
	"NO",
	"NP",
	"NR",
	"NU",
	"NZ",
	"OM",
	"PA",
	"PE",
	"PF",
	"PG",
	"PH",
	"PK",
	"PL",
	"PM",
	"PN",
	"PR",
	"PS",
	"PT",
	"PW",
	"PY",
	"QA",
	"RE",
	"RO",
	"RS",
	"RU",
	"RW",
	"SA",
	"SB",
	"SC",
	"SD",
	"SE",
	"SG",
	"SH",
	"SI",
	"SJ",
	"SK",
	"SL",
	"SM",
	"SN",
	"SO",
	"SR",
	"SS",
	"ST",
	"SV",
	"SX",
	"SY",
	"SZ",
	"TC",
	"TD",
	"TG",
	"TH",
	"TJ",
	"TK",
	"TL",
	"TM",
	"TN",
	"TO",
	"TR",
	"TT",
	"TV",
	"TW",
	"TZ",
	"UA",
	"UG",
	"US",
	"UY",
	"UZ",
	"VA",
	"VC",
	"VE",
	"VG",
	"VI",
	"VN",
	"VU",
	"WF",
	"WS",
	"XK",
	"YE",
	"YT",
	"ZA",
	"ZM",
	"ZW",
}

func (v *CountryCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CountryCode(value)
	for _, existing := range AllowedCountryCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CountryCode", value)
}

// NewCountryCodeFromValue returns a pointer to a valid CountryCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCountryCodeFromValue(v string) (*CountryCode, error) {
	ev := CountryCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CountryCode: valid values are %v", v, AllowedCountryCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CountryCode) IsValid() bool {
	for _, existing := range AllowedCountryCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CountryCode value
func (v CountryCode) Ptr() *CountryCode {
	return &v
}

type NullableCountryCode struct {
	value *CountryCode
	isSet bool
}

func (v NullableCountryCode) Get() *CountryCode {
	return v.value
}

func (v *NullableCountryCode) Set(val *CountryCode) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryCode) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryCode(val *CountryCode) *NullableCountryCode {
	return &NullableCountryCode{value: val, isSet: true}
}

func (v NullableCountryCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

