/*
Xero Accounting API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.1
Contact: api@xero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchPaymentDeleteByUrlParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchPaymentDeleteByUrlParam{}

// BatchPaymentDeleteByUrlParam struct for BatchPaymentDeleteByUrlParam
type BatchPaymentDeleteByUrlParam struct {
	// The status of the batch payment.
	Status string `json:"Status"`
}

type _BatchPaymentDeleteByUrlParam BatchPaymentDeleteByUrlParam

// NewBatchPaymentDeleteByUrlParam instantiates a new BatchPaymentDeleteByUrlParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchPaymentDeleteByUrlParam(status string) *BatchPaymentDeleteByUrlParam {
	this := BatchPaymentDeleteByUrlParam{}
	this.Status = status
	return &this
}

// NewBatchPaymentDeleteByUrlParamWithDefaults instantiates a new BatchPaymentDeleteByUrlParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchPaymentDeleteByUrlParamWithDefaults() *BatchPaymentDeleteByUrlParam {
	this := BatchPaymentDeleteByUrlParam{}
	var status string = "DELETED"
	this.Status = status
	return &this
}

// GetStatus returns the Status field value
func (o *BatchPaymentDeleteByUrlParam) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BatchPaymentDeleteByUrlParam) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BatchPaymentDeleteByUrlParam) SetStatus(v string) {
	o.Status = v
}

func (o BatchPaymentDeleteByUrlParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchPaymentDeleteByUrlParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Status"] = o.Status
	return toSerialize, nil
}

func (o *BatchPaymentDeleteByUrlParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchPaymentDeleteByUrlParam := _BatchPaymentDeleteByUrlParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchPaymentDeleteByUrlParam)

	if err != nil {
		return err
	}

	*o = BatchPaymentDeleteByUrlParam(varBatchPaymentDeleteByUrlParam)

	return err
}

type NullableBatchPaymentDeleteByUrlParam struct {
	value *BatchPaymentDeleteByUrlParam
	isSet bool
}

func (v NullableBatchPaymentDeleteByUrlParam) Get() *BatchPaymentDeleteByUrlParam {
	return v.value
}

func (v *NullableBatchPaymentDeleteByUrlParam) Set(val *BatchPaymentDeleteByUrlParam) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchPaymentDeleteByUrlParam) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchPaymentDeleteByUrlParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchPaymentDeleteByUrlParam(val *BatchPaymentDeleteByUrlParam) *NullableBatchPaymentDeleteByUrlParam {
	return &NullableBatchPaymentDeleteByUrlParam{value: val, isSet: true}
}

func (v NullableBatchPaymentDeleteByUrlParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchPaymentDeleteByUrlParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


